export const SAMPLES: Record<string, { language: string; code: string }> = {
  Python: {
    language: 'python',
    code: [
      '# Python – runs in your browser',
      'print("Hello from Python!")',
      'print("2 + 2 =", 2 + 2)',
      '',
      'nums = [1, 2, 3, 4, 5]',
      'print("Squares:", [n**2 for n in nums])',
      '',
      'def greet(name):',
      '    return f"Hi, {name}!"',
      '',
      'print(greet("Developer"))',
      '',
    ].join('\n'),
  },
  JavaScript: {
    language: 'javascript',
    code: [
      '// JavaScript',
      'console.log("Hello from JavaScript!");',
      'console.log("2 + 2 =", 2 + 2);',
      '',
      'const nums = [1, 2, 3, 4, 5];',
      'console.log("Squares:", nums.map(n => n ** 2));',
      '',
      'function greet(name) {',
      '  return "Hi, " + name + "!";',
      '}',
      'console.log(greet("Developer"));',
      '',
    ].join('\n'),
  },
  TypeScript: {
    language: 'typescript',
    code: [
      '// TypeScript',
      'const message: string = "Hello from TypeScript!";',
      'console.log(message);',
      '',
      'function add(a: number, b: number): number {',
      '  return a + b;',
      '}',
      'console.log("3 + 5 =", add(3, 5));',
      '',
    ].join('\n'),
  },
  HTML: {
    language: 'html',
    code: [
      '<!DOCTYPE html>',
      '<html>',
      '<head>',
      '  <style>',
      '    body {',
      '      font-family: system-ui, sans-serif;',
      '      display: flex;',
      '      justify-content: center;',
      '      align-items: center;',
      '      height: 100vh;',
      '      margin: 0;',
      '      background: linear-gradient(135deg, #0f172a, #1e293b);',
      '      color: #e2e8f0;',
      '    }',
      '    h1 { color: #34d399; font-size: 1.8rem; }',
      '  </style>',
      '</head>',
      '<body>',
      '  <h1>Hello from HTML</h1>',
      '</body>',
      '</html>',
      '',
    ].join('\n'),
  },
  'Python Data': {
    language: 'python',
    code: [
      '# Simple data analysis',
      'data = [23, 45, 12, 67, 34, 89, 21, 56]',
      '',
      'print("Data:", data)',
      'print("Count:", len(data))',
      'print("Sum:", sum(data))',
      'print("Average:", round(sum(data) / len(data), 2))',
      'print("Min:", min(data), "| Max:", max(data))',
      'print("Sorted:", sorted(data))',
      '',
    ].join('\n'),
  },
}
