export const SAMPLES: Record<string, { language: string; code: string }> = {
  'iPhone Home': {
    language: 'html',
    code: [
      '<!DOCTYPE html>',
      '<html>',
      '<head>',
      '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">',
      '<style>',
      '  * { box-sizing: border-box; margin: 0; padding: 0; }',
      '  body {',
      '    font-family: -apple-system, BlinkMacSystemFont, system-ui, sans-serif;',
      '    background: #000;',
      '    display: flex;',
      '    justify-content: center;',
      '    align-items: center;',
      '    min-height: 100vh;',
      '    padding: 12px;',
      '  }',
      '  .phone {',
      '    width: 100%;',
      '    max-width: 320px;',
      '    aspect-ratio: 9/19.5;',
      '    background: linear-gradient(160deg, #1a2744, #0d1526);',
      '    border-radius: 36px;',
      '    padding: 12px;',
      '    box-shadow: 0 0 0 3px #222, 0 20px 60px rgba(0,0,0,0.5);',
      '    display: flex;',
      '    flex-direction: column;',
      '    overflow: hidden;',
      '    position: relative;',
      '  }',
      '  .notch {',
      '    width: 100px; height: 24px; background: #000;',
      '    border-radius: 0 0 14px 14px; margin: 0 auto 8px;',
      '  }',
      '  .status {',
      '    display: flex; justify-content: space-between;',
      '    color: #fff; font-size: 12px; font-weight: 600;',
      '    padding: 0 8px 12px;',
      '  }',
      '  .widgets {',
      '    display: grid; grid-template-columns: 1fr 1fr; gap: 10px;',
      '    padding: 0 4px 14px;',
      '  }',
      '  .widget {',
      '    border-radius: 18px; padding: 12px;',
      '    color: #fff; min-height: 70px;',
      '  }',
      '  .w-weather { background: linear-gradient(135deg, #1e3a5f, #2d5a87); }',
      '  .w-cal { background: #fff; color: #111; }',
      '  .w-cal .day { color: #e11; font-size: 11px; font-weight: 700; }',
      '  .w-cal .num { font-size: 28px; font-weight: 700; }',
      '  .apps {',
      '    display: grid; grid-template-columns: repeat(4, 1fr);',
      '    gap: 14px 8px; padding: 8px 4px; flex: 1;',
      '  }',
      '  .app {',
      '    display: flex; flex-direction: column; align-items: center; gap: 4px;',
      '    cursor: pointer; user-select: none;',
      '  }',
      '  .app:active { transform: scale(0.9); }',
      '  .icon {',
      '    width: 52px; height: 52px; border-radius: 14px;',
      '    display: flex; align-items: center; justify-content: center;',
      '    font-size: 24px; color: #fff;',
      '  }',
      '  .app span { font-size: 10px; color: #fff; text-align: center; }',
      '  .dock {',
      '    display: flex; justify-content: center; gap: 16px;',
      '    background: rgba(255,255,255,0.15); backdrop-filter: blur(20px);',
      '    border-radius: 28px; padding: 10px 18px; margin: 8px 4px 4px;',
      '  }',
      '  .dock .icon { width: 48px; height: 48px; border-radius: 12px; }',
      '  #screen2 { display: none; }',
      '  .back-btn {',
      '    color: #3b82f6; font-size: 15px; padding: 12px;',
      '    cursor: pointer; font-weight: 500;',
      '  }',
      '  .page-title { color: #fff; text-align: center; font-size: 18px; font-weight: 600; padding: 8px; }',
      '</style>',
      '</head>',
      '<body>',
      '<div class="phone">',
      '  <div id="home">',
      '    <div class="notch"></div>',
      '    <div class="status"><span>9:41</span><span>5G 100%</span></div>',
      '    <div class="widgets">',
      '      <div class="widget w-weather">',
      '        <div style="font-size:12px;opacity:0.8">Lagos</div>',
      '        <div style="font-size:28px;font-weight:700">77°</div>',
      '        <div style="font-size:11px;opacity:0.7">Rainy</div>',
      '      </div>',
      '      <div class="widget w-cal">',
      '        <div class="day">FRIDAY</div>',
      '        <div class="num">18</div>',
      '        <div style="font-size:11px;color:#666">No events</div>',
      '      </div>',
      '    </div>',
      '    <div class="apps">',
      '      <div class="app" onclick="openApp(\'Camera\')"><div class="icon" style="background:#333">📷</div><span>Camera</span></div>',
      '      <div class="app" onclick="openApp(\'Photos\')"><div class="icon" style="background:linear-gradient(#f0a,#e50)"></div><span>Photos</span></div>',
      '      <div class="app" onclick="openApp(\'Settings\')"><div class="icon" style="background:#8e8e93">⚙️</div><span>Settings</span></div>',
      '      <div class="app" onclick="openApp(\'Messages\')"><div class="icon" style="background:#34c759">💬</div><span>Messages</span></div>',
      '      <div class="app" onclick="openApp(\'Safari\')"><div class="icon" style="background:linear-gradient(#58f,#28d)">🧭</div><span>Safari</span></div>',
      '      <div class="app" onclick="openApp(\'Music\')"><div class="icon" style="background:linear-gradient(#f36,#e12)">🎵</div><span>Music</span></div>',
      '      <div class="app" onclick="openApp(\'Maps\')"><div class="icon" style="background:#34c759">🗺️</div><span>Maps</span></div>',
      '      <div class="app" onclick="openApp(\'Clock\')"><div class="icon" style="background:#1c1c1e">🕐</div><span>Clock</span></div>',
      '    </div>',
      '    <div class="dock">',
      '      <div class="icon" style="background:#34c759">📞</div>',
      '      <div class="icon" style="background:linear-gradient(#58f,#28d)">🧭</div>',
      '      <div class="icon" style="background:#34c759">💬</div>',
      '      <div class="icon" style="background:linear-gradient(#f36,#e12)">🎵</div>',
      '    </div>',
      '  </div>',
      '  <div id="screen2">',
      '    <div class="notch"></div>',
      '    <div class="back-btn" onclick="goHome()">‹ Back</div>',
      '    <div class="page-title" id="appTitle">App</div>',
      '    <div style="flex:1;display:flex;align-items:center;justify-content:center;color:#888;font-size:15px;padding:20px;text-align:center" id="appBody">',
      '      App content here',
      '    </div>',
      '  </div>',
      '</div>',
      '<script>',
      '  function openApp(name) {',
      '    document.getElementById("home").style.display = "none";',
      '    document.getElementById("screen2").style.display = "flex";',
      '    document.getElementById("screen2").style.flexDirection = "column";',
      '    document.getElementById("screen2").style.flex = "1";',
      '    document.getElementById("appTitle").textContent = name;',
      '    document.getElementById("appBody").textContent = name + " app is open. Tap Back to return home.";',
      '  }',
      '  function goHome() {',
      '    document.getElementById("screen2").style.display = "none";',
      '    document.getElementById("home").style.display = "block";',
      '  }',
      '</script>',
      '</body>',
      '</html>',
    ].join('\n'),
  },
  Python: {
    language: 'python',
    code: [
      'print("Hello from Python!")',
      'print("2 + 2 =", 2 + 2)',
      '',
      'nums = [1, 2, 3, 4, 5]',
      'print("Squares:", [n**2 for n in nums])',
      '',
      'def greet(name):',
      '    return f"Hi, {name}!"',
      '',
      'print(greet("Developer"))',
    ].join('\n'),
  },
  JavaScript: {
    language: 'javascript',
    code: [
      'console.log("Hello from JavaScript!");',
      'console.log("2 + 2 =", 2 + 2);',
      '',
      'const nums = [1, 2, 3, 4, 5];',
      'console.log("Squares:", nums.map(n => n ** 2));',
      '',
      'function greet(name) {',
      '  return "Hi, " + name + "!";',
      '}',
      'console.log(greet("Developer"));',
    ].join('\n'),
  },
  HTML: {
    language: 'html',
    code: [
      '<!DOCTYPE html>',
      '<html>',
      '<head>',
      '<meta name="viewport" content="width=device-width, initial-scale=1">',
      '<style>',
      '  body {',
      '    font-family: system-ui, sans-serif;',
      '    display: flex; justify-content: center; align-items: center;',
      '    height: 100vh; margin: 0;',
      '    background: linear-gradient(135deg, #0f172a, #1e293b);',
      '    color: #e2e8f0;',
      '  }',
      '  h1 { color: #34d399; }',
      '  button {',
      '    margin-top: 16px; padding: 12px 24px; border: none;',
      '    border-radius: 12px; background: #10b981; color: white;',
      '    font-size: 16px; cursor: pointer;',
      '  }',
      '</style>',
      '</head>',
      '<body>',
      '  <div style="text-align:center">',
      '    <h1>Hello from HTML</h1>',
      '    <button onclick="alert(\'It works!\')">Tap me</button>',
      '  </div>',
      '</body>',
      '</html>',
    ].join('\n'),
  },
}
