export const SAMPLES: Record<string, { language: string; code: string }> = {
  'iPhone Home': {
    language: 'html',
    code: [
      '<!DOCTYPE html>',
      '<html>',
      '<head>',
      '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">',
      '<style>',
      '  * { box-sizing: border-box; margin: 0; padding: 0; }',
      '  html, body { height: 100%; overflow: hidden; }',
      '  body {',
      '    font-family: -apple-system, BlinkMacSystemFont, system-ui, sans-serif;',
      '    background: linear-gradient(165deg, #0a1e38 0%, #1a4a6e 40%, #0d3050 100%);',
      '    color: #fff;',
      '    padding: 52px 14px 28px;',
      '  }',
      '  .status { display: flex; justify-content: space-between; font-size: 12px; font-weight: 600; margin-bottom: 14px; padding: 0 4px; }',
      '  .weather {',
      '    background: rgba(30,60,100,0.75); border-radius: 18px; padding: 14px 16px; margin-bottom: 18px;',
      '  }',
      '  .weather .loc { font-size: 15px; opacity: 0.9; }',
      '  .weather .temp { font-size: 36px; font-weight: 200; }',
      '  .apps { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px 10px; }',
      '  .app { display: flex; flex-direction: column; align-items: center; gap: 6px; cursor: pointer; }',
      '  .app:active { transform: scale(0.9); }',
      '  .icon { width: 58px; height: 58px; border-radius: 14px; display: flex; align-items: center; justify-content: center; font-size: 26px; }',
      '  .app span { font-size: 11px; text-align: center; text-shadow: 0 1px 2px rgba(0,0,0,0.5); }',
      '</style>',
      '</head>',
      '<body>',
      '  <div class="status"><span>9:41</span><span>5G 100%</span></div>',
      '  <div class="weather">',
      '    <div class="loc">London</div>',
      '    <div class="temp">11°</div>',
      '    <div style="font-size:13px;opacity:0.85">Mostly Cloudy · H:17° L:10°</div>',
      '  </div>',
      '  <div class="apps">',
      '    <div class="app"><div class="icon" style="background:#30d158">📹</div><span>FaceTime</span></div>',
      '    <div class="app"><div class="icon" style="background:#ff3b30">📅</div><span>Calendar</span></div>',
      '    <div class="app"><div class="icon" style="background:conic-gradient(#f2d,#f90,#fc0,#3c5,#08f,#85d,#f2d)">🖼️</div><span>Photos</span></div>',
      '    <div class="app"><div class="icon" style="background:#8e8e93">📷</div><span>Camera</span></div>',
      '    <div class="app"><div class="icon" style="background:#007aff">✉️</div><span>Mail</span></div>',
      '    <div class="app"><div class="icon" style="background:#ffcc00">📝</div><span>Notes</span></div>',
      '    <div class="app"><div class="icon" style="background:#1c1c1e">🕐</div><span>Clock</span></div>',
      '    <div class="app"><div class="icon" style="background:#8e8e93">⚙️</div><span>Settings</span></div>',
      '  </div>',
      '</body>',
      '</html>',
    ].join('\n'),
  },
  Dart: {
    language: 'dart',
    code: [
      'void main() {',
      '  print("Hello from Dart!");',
      '  print("2 + 2 = ${2 + 2}");',
      '',
      '  final nums = [1, 2, 3, 4, 5];',
      '  print("Squares: ${nums.map((n) => n * n).toList()}");',
      '',
      '  String greet(String name) => "Hi, $name!";',
      '  print(greet("Developer"));',
      '}',
    ].join('\n'),
  },
  Python: {
    language: 'python',
    code: [
      'print("Hello from Python!")',
      'print("2 + 2 =", 2 + 2)',
      '',
      'nums = [1, 2, 3, 4, 5]',
      'print("Squares:", [n**2 for n in nums])',
      '',
      'def greet(name):',
      '    return f"Hi, {name}!"',
      '',
      'print(greet("Developer"))',
    ].join('\n'),
  },
  JavaScript: {
    language: 'javascript',
    code: [
      'console.log("Hello from JavaScript!");',
      'console.log("2 + 2 =", 2 + 2);',
      '',
      'const nums = [1, 2, 3, 4, 5];',
      'console.log("Squares:", nums.map(n => n ** 2));',
      '',
      'function greet(name) {',
      '  return "Hi, " + name + "!";',
      '}',
      'console.log(greet("Developer"));',
    ].join('\n'),
  },
  HTML: {
    language: 'html',
    code: [
      '<!DOCTYPE html>',
      '<html>',
      '<head>',
      '<meta name="viewport" content="width=device-width, initial-scale=1">',
      '<style>',
      '  body {',
      '    font-family: system-ui, sans-serif;',
      '    display: flex; justify-content: center; align-items: center;',
      '    height: 100vh; margin: 0;',
      '    background: linear-gradient(135deg, #0f172a, #1e293b);',
      '    color: #e2e8f0;',
      '  }',
      '  h1 { color: #34d399; }',
      '  button {',
      '    margin-top: 16px; padding: 12px 24px; border: none;',
      '    border-radius: 12px; background: #10b981; color: white;',
      '    font-size: 16px; cursor: pointer;',
      '  }',
      '</style>',
      '</head>',
      '<body>',
      '  <div style="text-align:center">',
      '    <h1>Hello from HTML</h1>',
      '    <button onclick="alert(\'It works!\')">Tap me</button>',
      '  </div>',
      '</body>',
      '</html>',
    ].join('\n'),
  },
}
